export interface School {
  id: string;
  nameEn: string;
  nameAr: string;
  region: string;
  area: string;
  academicStage: string;
  schoolGender: string;
  numberOfStudents: number;
  status: string;
}

export const SCHOOLS: School[] = [
  {
    id: "sample-school",
    nameEn: "2 Sample School",
    nameAr: "مدرسة نموذجية 2",
    region: "East Region",
    area: "Arad Zone",
    academicStage: "Primary",
    schoolGender: "Male",
    numberOfStudents: 300,
    status: "active",
  },
  {
    id: "arad-1",
    nameEn: "Al-Khwarizmi Primary School for Boys",
    nameAr: "مدرسة الخوارزمي الابتدائية للبنين",
    region: "East Region",
    area: "Arad Zone",
    academicStage: "Primary",
    schoolGender: "Male",
    numberOfStudents: 750,
    status: "active",
  },
  {
    id: "arad-2",
    nameEn: "Arad Intermediate School for Girls",
    nameAr: "مدرسة عراد الإعدادية للبنات",
    region: "East Region",
    area: "Arad Zone",
    academicStage: "Primary",
    schoolGender: "Female",
    numberOfStudents: 891,
    status: "active",
  },
  {
    id: "arad-3",
    nameEn: "Arad Primary School for Boys",
    nameAr: "مدرسة عراد الابتدائية للبنين",
    region: "East Region",
    area: "Arad Zone",
    academicStage: "Primary",
    schoolGender: "Male",
    numberOfStudents: 359,
    status: "active",
  },
  {
    id: "arad-4",
    nameEn: "Arad Primary School for Girls",
    nameAr: "مدرسة عراد الابتدائية للبنات",
    region: "East Region",
    area: "Arad Zone",
    academicStage: "Primary",
    schoolGender: "Female",
    numberOfStudents: 604,
    status: "active",
  },
  {
    id: "arad-5",
    nameEn: "Arad Intermediate School for Boys",
    nameAr: "مدرسة عراد الإعدادية للبنين",
    region: "North Region",
    area: "Arad Zone",
    academicStage: "Intermediate (Preparatory)",
    schoolGender: "Male",
    numberOfStudents: 880,
    status: "active",
  },
  {
    id: "arad-6",
    nameEn: "Al-Rawba Primary School for Girls",
    nameAr: "مدرسة العروبة الابتدائية للبنات",
    region: "East Region",
    area: "Arad Zone",
    academicStage: "Primary",
    schoolGender: "Female",
    numberOfStudents: 1100,
    status: "active",
  },
  {
    id: "asker-1a",
    nameEn: "H.H. Shaikha Moza bint Hamad Al Khalifa Primary School (Girls) - 1",
    nameAr: "مدرسة سمو الشيخة موزة بنت حمد آل خليفة الابتدائية للبنات - 1",
    region: "West Region",
    area: "Asker Area",
    academicStage: "Primary",
    schoolGender: "Female",
    numberOfStudents: 1600,
    status: "active",
  },
  {
    id: "asker-1b",
    nameEn: "H.H. Shaikha Moza bint Hamad Al Khalifa Primary School (Girls) - 2",
    nameAr: "مدرسة سمو الشيخة موزة بنت حمد آل خليفة الابتدائية للبنات - 2",
    region: "West Region",
    area: "Asker Area",
    academicStage: "Primary",
    schoolGender: "Female",
    numberOfStudents: 1600,
    status: "active",
  },
  {
    id: "asker-1c",
    nameEn: "H.H. Shaikha Moza bint Hamad Al Khalifa Intermediate School (Girls)",
    nameAr: "مدرسة سمو الشيخة موزة بنت حمد آل خليفة الإعدادية للبنات",
    region: "West Region",
    area: "Asker Area",
    academicStage: "Intermediate (Preparatory)",
    schoolGender: "Female",
    numberOfStudents: 1600,
    status: "active",
  },
  {
    id: "asker-1",
    nameEn: "H.H. Shaikha Moza bint Hamad Al Khalifa Secondary School (Girls)",
    nameAr: "مدرسة سمو الشيخة موزة بنت حمد آل خليفة الثانوية للبنات",
    region: "West Region",
    area: "Asker Area",
    academicStage: "Secondary & Vocational",
    schoolGender: "Female",
    numberOfStudents: 1600,
    status: "active",
  },
  {
    id: "asker-2",
    nameEn: "Jaw Primary School for Boys",
    nameAr: "مدرسة جو الابتدائية للبنين",
    region: "East Region",
    area: "Asker Area",
    academicStage: "Primary",
    schoolGender: "Male",
    numberOfStudents: 500,
    status: "active",
  },
  {
    id: "asker-3",
    nameEn: "Askar Primary & Intermediate School for Boys",
    nameAr: "مدرسة عسكر الابتدائية للبنين",
    region: "West Region",
    area: "Asker Area",
    academicStage: "Primary & Intermediate",
    schoolGender: "Male",
    numberOfStudents: 600,
    status: "active",
  },
  {
    id: "asker-4",
    nameEn: "Shaikh Nasser Center For Science & Technology",
    nameAr: "مركز الشيخ ناصر للعلوم والتكنولوجيا",
    region: "West Region",
    area: "Asker Area",
    academicStage: "Secondary & Vocational",
    schoolGender: "Male",
    numberOfStudents: 600,
    status: "active",
  },
  {
    id: "galali-1",
    nameEn: "Al-Dair Primary & Intermediate School for Girls",
    nameAr: "مدرسة الدير الابتدائية الإعدادية للبنات",
    region: "South Region",
    area: "Galali Area",
    academicStage: "Primary & Intermediate",
    schoolGender: "Female",
    numberOfStudents: 1200,
    status: "active",
  },
  {
    id: "galali-2",
    nameEn: "Al-Dair Primary School for Boys",
    nameAr: "مدرسة الدير الابتدائية للبنين",
    region: "South Region",
    area: "Galali Area",
    academicStage: "Primary",
    schoolGender: "Male",
    numberOfStudents: 693,
    status: "active",
  },
  {
    id: "galali-3",
    nameEn: "Ruqiya Primary School for Girls",
    nameAr: "مدرسة رقية الابتدائية للبنات",
    region: "East Region",
    area: "Galali Area",
    academicStage: "Primary",
    schoolGender: "Female",
    numberOfStudents: 1500,
    status: "active",
  },
  {
    id: "galali-4",
    nameEn: "Samaheej Intermediate School for Boys",
    nameAr: "مدرسة سماهيج الإعدادية للبنين",
    region: "North Region",
    area: "Galali Area",
    academicStage: "Intermediate (Preparatory)",
    schoolGender: "Male",
    numberOfStudents: 660,
    status: "active",
  },
  {
    id: "galali-5",
    nameEn: "Qalali Primary School for Boys",
    nameAr: "مدرسة قلالي الابتدائية للبنين",
    region: "South Region",
    area: "Galali Area",
    academicStage: "Primary & Intermediate",
    schoolGender: "Male",
    numberOfStudents: 1100,
    status: "active",
  },
  {
    id: "galali-6",
    nameEn: "Al Hidd Primary & Intermediate School for Girls",
    nameAr: "مدرسة الحد الابتدائية الاعدادية للبنات",
    region: "South Region",
    area: "Galali Area",
    academicStage: "Primary & Intermediate",
    schoolGender: "Female",
    numberOfStudents: 1571,
    status: "active",
  },
];

/** Get active schools only */
export const getActiveSchools = (): School[] => {
  return SCHOOLS.filter((s) => s.status === "active");
};

/** Get school display name based on language */
export const getSchoolDisplayName = (school: School, lang: string): string => {
  if (lang === "ar" && school.nameAr) return school.nameAr;
  return school.nameEn;
};
