export interface School {
  id: string;
  nameEn: string;
  nameAr: string;
  region: string;
  area: string;
  academicStage: string;
  schoolGender: string;
  numberOfStudents: number;
  status: string;
}

export const SCHOOLS: School[] = [
  {
    id: "w-riff---4-0",
    nameEn: "Al-Fateh Secondary School for Boys",
    nameAr: "الفاتح الثانوية للبنين",
    region: "W/RIFF",
    area: "W/RIFF",
    academicStage: "Secondary",
    schoolGender: "Male",
    numberOfStudents: 500,
    status: "active",
  },
  {
    id: "manama---1-1",
    nameEn: "Al‑Ma'mun Primary School for Boys",
    nameAr: "مدرسة المأمون الابتدائية للبنين",
    region: "MANAMA",
    area: "MANAMA",
    academicStage: "Primary",
    schoolGender: "Male",
    numberOfStudents: 500,
    status: "active",
  },
  {
    id: "galali---3-2",
    nameEn: "Ruqiya Primary School for Girls",
    nameAr: "مدرسة رقية الابتدائية للبنات",
    region: "GALALI",
    area: "GALALI",
    academicStage: "Primary",
    schoolGender: "Female",
    numberOfStudents: 500,
    status: "active",
  },
  {
    id: "hajiyath---5-3",
    nameEn: "Fatima bint Al‑Khattab Primary School for Girls",
    nameAr: "مدرسة فاطمة بنت الخطاب الابتدائية للبنات",
    region: "HAJIYATH",
    area: "HAJIYATH",
    academicStage: "Primary",
    schoolGender: "Female",
    numberOfStudents: 500,
    status: "active",
  },
  {
    id: "hajiyath---3-4",
    nameEn: "East Riffa Secondary School for Boys",
    nameAr: "الرفاع الشرقي الثانوية للبنين",
    region: "HAJIYATH",
    area: "HAJIYATH",
    academicStage: "Secondary",
    schoolGender: "Male",
    numberOfStudents: 500,
    status: "active",
  },
  {
    id: "galali---5-5",
    nameEn: "Qalali Primary School for Biys",
    nameAr: "مدرسة قلالي الابتدائية للبنين",
    region: "GALALI",
    area: "GALALI",
    academicStage: "Primary",
    schoolGender: "Male",
    numberOfStudents: 500,
    status: "active",
  },
  {
    id: "muhrq---2-6",
    nameEn: "Busaiteen Primary School for Girls",
    nameAr: "مدرسة السبتين الابتدائية للبنات",
    region: "MUHRQ",
    area: "MUHRQ",
    academicStage: "Primary",
    schoolGender: "Female",
    numberOfStudents: 500,
    status: "active",
  },
  {
    id: "muhrq---4-7",
    nameEn: "Busaiteen Intermediate School for Girls",
    nameAr: "مدرسة السبتين الإعدادية للبنات",
    region: "MUHRQ",
    area: "MUHRQ",
    academicStage: "Intermediate",
    schoolGender: "Female",
    numberOfStudents: 500,
    status: "active",
  },
  {
    id: "muhrq---7-8",
    nameEn: "Khadija Al‑Kubra Intermediate School for Girls",
    nameAr: "مدرسة خديجة الكبرى الإعدادية للبنات",
    region: "MUHRQ",
    area: "MUHRQ",
    academicStage: "Intermediate",
    schoolGender: "Female",
    numberOfStudents: 500,
    status: "active",
  },
  {
    id: "muhrq---8-9",
    nameEn: "Maryam bint Imran Primary School for Girls",
    nameAr: "مدرسة مريم بنت عمران الابتدائية للبنات",
    region: "MUHRQ",
    area: "MUHRQ",
    academicStage: "Primary",
    schoolGender: "Female",
    numberOfStudents: 500,
    status: "active",
  },
  {
    id: "galali---1-10",
    nameEn: "Al‑Dair Primary & Intermediate School for Girls",
    nameAr: "مدرسة الدير الابتدائية الإعدادية للبنات",
    region: "GALALI",
    area: "GALALI",
    academicStage: "Primary",
    schoolGender: "Female",
    numberOfStudents: 500,
    status: "active",
  },
  {
    id: "galali---2-11",
    nameEn: "Al‑Dair Primary School for Boys",
    nameAr: "مدرسة الدير الابتدائية للبنين",
    region: "GALALI",
    area: "GALALI",
    academicStage: "Primary",
    schoolGender: "Male",
    numberOfStudents: 500,
    status: "active",
  },
  {
    id: "arad---1-12",
    nameEn: "Al‑Khwarizmi Primary School for Boys",
    nameAr: "مدرسة الخوارزمي الابتدائية للبنين",
    region: "ARAD",
    area: "ARAD",
    academicStage: "Primary",
    schoolGender: "Male",
    numberOfStudents: 500,
    status: "active",
  },
  {
    id: "arad---3-13",
    nameEn: "Arad Primary School for Boys",
    nameAr: "مدرسة عراد الابتدائية للبنين",
    region: "ARAD",
    area: "ARAD",
    academicStage: "Primary",
    schoolGender: "Male",
    numberOfStudents: 500,
    status: "active",
  },
  {
    id: "arad---4-14",
    nameEn: "Arad Primary School for Girls",
    nameAr: "مدرسة عراد الابتدائية للبنات",
    region: "ARAD",
    area: "ARAD",
    academicStage: "Primary",
    schoolGender: "Female",
    numberOfStudents: 500,
    status: "active",
  },
  {
    id: "arad---2-15",
    nameEn: "Arad Intermediate School for Girls",
    nameAr: "مدرسة عراد الإعدادية للبنين",
    region: "ARAD",
    area: "ARAD",
    academicStage: "Intermediate",
    schoolGender: "Male",
    numberOfStudents: 500,
    status: "active",
  },
  {
    id: "arad---6-16",
    nameEn: "Al‑Rawba Primary School for Girls",
    nameAr: "مدرسة العروبة الابتدائية للبنات",
    region: "ARAD",
    area: "ARAD",
    academicStage: "Primary",
    schoolGender: "Female",
    numberOfStudents: 500,
    status: "active",
  },
  {
    id: "w-riff---1-17",
    nameEn: "East Riffa Primary School for Boys",
    nameAr: "مدرسة الرفاع الشرقي الابتدائية للبنين",
    region: "W/RIFF",
    area: "W/RIFF",
    academicStage: "Primary",
    schoolGender: "Male",
    numberOfStudents: 500,
    status: "active",
  },
  {
    id: "w-riff---2-18",
    nameEn: "Huneniya Primary School for Girls",
    nameAr: "مدرسة الحينية الابتدائية الإعدادية للبنات",
    region: "W/RIFF",
    area: "W/RIFF",
    academicStage: "Primary",
    schoolGender: "Female",
    numberOfStudents: 500,
    status: "active",
  },
  {
    id: "w-riff---5-19",
    nameEn: "West Riffa Primary School for Girls",
    nameAr: "مدرسة الرفاع الغربي الابتدائية للبنات",
    region: "W/RIFF",
    area: "W/RIFF",
    academicStage: "Primary",
    schoolGender: "Female",
    numberOfStudents: 500,
    status: "active",
  },
  {
    id: "w-riff---6-20",
    nameEn: "West Riffa Primary School for Boys",
    nameAr: "مدرسة الرفاع الغربي الابتدائية للبنين",
    region: "W/RIFF",
    area: "W/RIFF",
    academicStage: "Primary",
    schoolGender: "Male",
    numberOfStudents: 500,
    status: "active",
  },
  {
    id: "w-riff---7-21",
    nameEn: "East Riffa Primary School for Girls",
    nameAr: "مدرسة الرفاع الشرقي الابتدائية للبنات",
    region: "W/RIFF",
    area: "W/RIFF",
    academicStage: "Primary",
    schoolGender: "Female",
    numberOfStudents: 500,
    status: "active",
  },
  {
    id: "w-riff---8-22",
    nameEn: "West Riffa Secondary School for Girls",
    nameAr: "الرفاع الغربي الثانوية للبنات",
    region: "W/RIFF",
    area: "W/RIFF",
    academicStage: "Secondary",
    schoolGender: "Female",
    numberOfStudents: 500,
    status: "active",
  },
  {
    id: "w-riff---9-23",
    nameEn: "West Riffa Intermediate School for Girls",
    nameAr: "مدرسة الرفاع الغربي الإعدادية للبنات",
    region: "W/RIFF",
    area: "W/RIFF",
    academicStage: "Intermediate",
    schoolGender: "Female",
    numberOfStudents: 500,
    status: "active",
  },
  {
    id: "hajiyath---1-24",
    nameEn: "Al-Andalus Primary School for Girls",
    nameAr: "مدرسة الأندلس الابتدائية للبنات",
    region: "HAJIYATH",
    area: "HAJIYATH",
    academicStage: "Primary",
    schoolGender: "Female",
    numberOfStudents: 500,
    status: "active",
  },
  {
    id: "hajiyath---4-25",
    nameEn: "Salah Al‑Din Al‑Ayyubi Primary School for Boys",
    nameAr: "مدرسة صلاح الدين الأيوبي الابتدائية للبنين",
    region: "HAJIYATH",
    area: "HAJIYATH",
    academicStage: "Primary",
    schoolGender: "Male",
    numberOfStudents: 500,
    status: "active",
  },
  {
    id: "hajiyath---6-26",
    nameEn: "East Riffa Intermediate School for Girls",
    nameAr: "مدرسة الرفاع الشرقي الإعدادية للبنات",
    region: "HAJIYATH",
    area: "HAJIYATH",
    academicStage: "Intermediate",
    schoolGender: "Female",
    numberOfStudents: 500,
    status: "active",
  },
  {
    id: "reem---1-27",
    nameEn: "Riffa Intermediate School for Boys",
    nameAr: "مدرسة الرفاع الإعدادية للبنين",
    region: "REEM",
    area: "REEM",
    academicStage: "Intermediate",
    schoolGender: "Male",
    numberOfStudents: 500,
    status: "active",
  },
  {
    id: "w-riff---3-28",
    nameEn: "Ibn Rushd Primary & Intermediate School for Boys",
    nameAr: "مدرسة ابن رشد الابتدائية الإعدادية للبنين",
    region: "W/RIFF",
    area: "W/RIFF",
    academicStage: "Primary",
    schoolGender: "Male",
    numberOfStudents: 500,
    status: "active",
  },
  {
    id: "hmdtown---2-29",
    nameEn: "Safra Primary School for Boys",
    nameAr: "مدرسة سافرة الابتدائية الإعدادية للبنين",
    region: "HMDTOWN",
    area: "HMDTOWN",
    academicStage: "Primary",
    schoolGender: "Male",
    numberOfStudents: 500,
    status: "active",
  },
  {
    id: "riffa-3-30",
    nameEn: "Wadi Al‑Seel Primary & Intermediate School for Boys",
    nameAr: "مدرسة وادي السيل الابتدائية الإعدادية للبنين",
    region: "RIFFA",
    area: "RIFFA",
    academicStage: "Primary",
    schoolGender: "Male",
    numberOfStudents: 500,
    status: "active",
  },
  {
    id: "muhrq---1-31",
    nameEn: "Al-Hidaya Al-Khalifia Secondary School for Boys",
    nameAr: "الهداية الخليفية الثانوية للبنين",
    region: "MUHRQ",
    area: "MUHRQ",
    academicStage: "Secondary",
    schoolGender: "Male",
    numberOfStudents: 500,
    status: "active",
  },
  {
    id: "muhrq---6-32",
    nameEn: "Sheikh Khalifa Bin Salman Institute of Technogy",
    nameAr: "معهد الشيخ خليفة بن سلمان للتكنولوجيا",
    region: "MUHRQ",
    area: "MUHRQ",
    academicStage: "Institute",
    schoolGender: "Mixed",
    numberOfStudents: 500,
    status: "active",
  },
  {
    id: "muhrq---9-33",
    nameEn: "Omar bin Al‑Khattab Primary & Intermediate School for Boys",
    nameAr: "عمر بن الخطاب الابتدائية الإعدادية للبنين",
    region: "MUHRQ",
    area: "MUHRQ",
    academicStage: "Primary",
    schoolGender: "Male",
    numberOfStudents: 500,
    status: "active",
  },
  {
    id: "galali---4-34",
    nameEn: "Samaheej Intermediate School for Boys",
    nameAr: "مدرسة سماهيج الإعدادية للبنين",
    region: "GALALI",
    area: "GALALI",
    academicStage: "Intermediate",
    schoolGender: "Male",
    numberOfStudents: 500,
    status: "active",
  },
  {
    id: "arad---5-35",
    nameEn: "Arad Intermediate School for Boys",
    nameAr: "مدرسة عراد الإعدادية للبنين",
    region: "ARAD",
    area: "ARAD",
    academicStage: "Intermediate",
    schoolGender: "Male",
    numberOfStudents: 500,
    status: "active",
  },
  {
    id: "muhrq---3-36",
    nameEn: "Busaiteen Primary School for Boys",
    nameAr: "مدرسة السبتين الابتدائية للبنين",
    region: "MUHRQ",
    area: "MUHRQ",
    academicStage: "Primary",
    schoolGender: "Male",
    numberOfStudents: 500,
    status: "active",
  },
  {
    id: "muhrq---5-37",
    nameEn: "Busaiteen Intermediate School for Boys",
    nameAr: "مدرسة السبتين الإعدادية للبنين",
    region: "MUHRQ",
    area: "MUHRQ",
    academicStage: "Intermediate",
    schoolGender: "Male",
    numberOfStudents: 500,
    status: "active",
  },
  {
    id: "asker---2-38",
    nameEn: "Jaw Primary School for Boys",
    nameAr: "مدرسة جو الابتدائية للبنين",
    region: "ASKER",
    area: "ASKER",
    academicStage: "Primary",
    schoolGender: "Male",
    numberOfStudents: 500,
    status: "active",
  },
  {
    id: "hajiyath---2-39",
    nameEn: "Malik bin Anas Primary School for Boys",
    nameAr: "مدرسة مالك بن أنس الابتدائية للبنين",
    region: "HAJIYATH",
    area: "HAJIYATH",
    academicStage: "Primary",
    schoolGender: "Male",
    numberOfStudents: 500,
    status: "active",
  },
  {
    id: "riffa-1-40",
    nameEn: "Safra Intermediate School for Girls",
    nameAr: "مدرسة سافرة الابتدائية الإعدادية للبنات",
    region: "RIFFA",
    area: "RIFFA",
    academicStage: "Primary",
    schoolGender: "Female",
    numberOfStudents: 500,
    status: "active",
  },
  {
    id: "riffa-4-41",
    nameEn: "Buri Primary School for Girls",
    nameAr: "مدرسة بوري الابتدائية للبنات",
    region: "RIFFA",
    area: "RIFFA",
    academicStage: "Primary",
    schoolGender: "Female",
    numberOfStudents: 500,
    status: "active",
  },
  {
    id: "riffa-5-42",
    nameEn: "Buri Primary School for Boys",
    nameAr: "مدرسة بوري الابتدائية للبنين",
    region: "RIFFA",
    area: "RIFFA",
    academicStage: "Primary",
    schoolGender: "Male",
    numberOfStudents: 500,
    status: "active",
  },
  {
    id: "hmdtown---6-43",
    nameEn: "Tadamon School Girls",
    nameAr: "التضامن الثانوية للبنات",
    region: "HMDTOWN",
    area: "HMDTOWN",
    academicStage: "Secondary",
    schoolGender: "Female",
    numberOfStudents: 500,
    status: "active",
  },
  {
    id: "saar---1-44",
    nameEn: "Aljazra  School Boys",
    nameAr: "مدرسة الجسرة  الابتدائية للبنين",
    region: "SAAR",
    area: "SAAR",
    academicStage: "Primary",
    schoolGender: "Male",
    numberOfStudents: 500,
    status: "active",
  },
  {
    id: "manama---2-45",
    nameEn: "AlMutanabi Primary Boys School",
    nameAr: "مدرسة المتنبي الابتدائية للبنين",
    region: "MANAMA",
    area: "MANAMA",
    academicStage: "Primary",
    schoolGender: "Male",
    numberOfStudents: 500,
    status: "active",
  },
  {
    id: "manama---3-46",
    nameEn: "Rabi'a Al‑Adawiya Primary School for Girls",
    nameAr: "مدرسة رابعة العدوية الابتدائية للبنات",
    region: "MANAMA",
    area: "MANAMA",
    academicStage: "Primary",
    schoolGender: "Female",
    numberOfStudents: 500,
    status: "active",
  },
  {
    id: "manama---4-47",
    nameEn: "Sukaina bint Al‑Hussain Primary School for Girls",
    nameAr: "مدرسة سكينة بنت الحسين الابتدائية للبنات",
    region: "MANAMA",
    area: "MANAMA",
    academicStage: "Primary",
    schoolGender: "Female",
    numberOfStudents: 500,
    status: "active",
  },
  {
    id: "manama---5-48",
    nameEn: "Aisha Umm Al‑Mu'mineen Primary School for Girls",
    nameAr: "مدرسة عائشة أم المؤمنين الابتدائية للبنات",
    region: "MANAMA",
    area: "MANAMA",
    academicStage: "Primary",
    schoolGender: "Female",
    numberOfStudents: 500,
    status: "active",
  },
  {
    id: "manama---6-49",
    nameEn: "Umm Ayman Primary school for Girls",
    nameAr: "مدرسة أم أيمن الابتدائية للبنات",
    region: "MANAMA",
    area: "MANAMA",
    academicStage: "Primary",
    schoolGender: "Female",
    numberOfStudents: 500,
    status: "active",
  },
  {
    id: "reem---2-50",
    nameEn: "Al-Ma'arifa Secondary School for Girls",
    nameAr: "المعرفة الثانوية للبنات",
    region: "REEM",
    area: "REEM",
    academicStage: "Secondary",
    schoolGender: "Female",
    numberOfStudents: 500,
    status: "active",
  },
  {
    id: "reem---3-51",
    nameEn: "Al‑Mustaqbal Primary School for Girls",
    nameAr: "مدرسة المستقبل الابتدائية للبنات",
    region: "REEM",
    area: "REEM",
    academicStage: "Primary",
    schoolGender: "Female",
    numberOfStudents: 500,
    status: "active",
  },
  {
    id: "reem---4-52",
    nameEn: "Uqba bin Nafi Primary School for Boys",
    nameAr: "مدرسة عقبة بن نافع الابتدائية للبنين",
    region: "REEM",
    area: "REEM",
    academicStage: "Primary",
    schoolGender: "Male",
    numberOfStudents: 500,
    status: "active",
  },
  {
    id: "reem---5-53",
    nameEn: "Arabian Gulf Primary School for Girls",
    nameAr: "مدرسة الخليج العربي الإعدادية للبنات",
    region: "REEM",
    area: "REEM",
    academicStage: "Primary",
    schoolGender: "Female",
    numberOfStudents: 500,
    status: "active",
  },
  {
    id: "asker---1b-54",
    nameEn: "H.H. Shaikha Moza bint Hamad Al Khalifa Primary School (Girls) - 2",
    nameAr: "",
    region: "B",
    area: "B",
    academicStage: "Primary",
    schoolGender: "Female",
    numberOfStudents: 500,
    status: "active",
  },
  {
    id: "asker---3-55",
    nameEn: "Askar Primary & Intermediate School for Boys",
    nameAr: "مدرسة عسكر الابتدائية للبنين",
    region: "ASKER",
    area: "ASKER",
    academicStage: "Primary",
    schoolGender: "Male",
    numberOfStudents: 500,
    status: "active",
  },
  {
    id: "w-riff---10-56",
    nameEn: "Ahmed Al‑Fateh Primary & Intermediate School for Boys",
    nameAr: "مدرسة أحمد الفاتح الابتدائية الإعدادية للبنين",
    region: "W/RIFF",
    area: "W/RIFF",
    academicStage: "Primary",
    schoolGender: "Male",
    numberOfStudents: 500,
    status: "active",
  },
  {
    id: "asker---1a-57",
    nameEn: "H.H. Shaikha Moza bint Hamad Al Khalifa Primary School (Girls) - 1",
    nameAr: "",
    region: "A",
    area: "A",
    academicStage: "Primary",
    schoolGender: "Female",
    numberOfStudents: 500,
    status: "active",
  },
  {
    id: "asker---1c-58",
    nameEn: "H.H. Shaikha Moza bint Hamad Al Khalifa Intermediate School (Girls)",
    nameAr: "",
    region: "C",
    area: "C",
    academicStage: "Intermediate",
    schoolGender: "Female",
    numberOfStudents: 500,
    status: "active",
  },
  {
    id: "asker---1-59",
    nameEn: "H.H. Shaikha Moza bint Hamad Al Khalifa Secondary School (Girls)",
    nameAr: "",
    region: "ASKER",
    area: "ASKER",
    academicStage: "Secondary",
    schoolGender: "Female",
    numberOfStudents: 500,
    status: "active",
  },
  {
    id: "2-sample-school-60",
    nameEn: "2 Sample School",
    nameAr: "",
    region: "Unknown",
    area: "Unknown",
    academicStage: "Primary",
    schoolGender: "Mixed",
    numberOfStudents: 500,
    status: "active",
  },
  {
    id: "asker---4-61",
    nameEn: "Shaikh Nasser Center For Science & Technology.",
    nameAr: "",
    region: "ASKER",
    area: "ASKER",
    academicStage: "Institute",
    schoolGender: "Mixed",
    numberOfStudents: 500,
    status: "active",
  },
  {
    id: "isa-town-1-62",
    nameEn: "Al-Taawun Secondary School for Boys",
    nameAr: "التعاون الثانوية للبنين",
    region: "ISA TOWN",
    area: "ISA TOWN",
    academicStage: "Secondary",
    schoolGender: "Male",
    numberOfStudents: 500,
    status: "active",
  },
  {
    id: "isa-town-13-63",
    nameEn: "Sheikh Isa bin Ali Secondary School for Boys",
    nameAr: "الشيخ عيسى بن علي الثانوية للبنين",
    region: "ISA TOWN",
    area: "ISA TOWN",
    academicStage: "Secondary",
    schoolGender: "Male",
    numberOfStudents: 500,
    status: "active",
  },
  {
    id: "isa-town-3-64",
    nameEn: "Al-Noor Secondary School for Girls",
    nameAr: "النور الثانوية للبنات",
    region: "ISA TOWN",
    area: "ISA TOWN",
    academicStage: "Secondary",
    schoolGender: "Female",
    numberOfStudents: 500,
    status: "active",
  },
  {
    id: "ht-rnd-abt-4-65",
    nameEn: "Ghazi Al-Qusaibi Secondary School for Girls",
    nameAr: "غازي القصيبي الثانوية للبنات",
    region: "HT RND ABT",
    area: "HT RND ABT",
    academicStage: "Secondary",
    schoolGender: "Female",
    numberOfStudents: 500,
    status: "active",
  },
  {
    id: "ht-rnd-abt-9a-66",
    nameEn: "Yathrib Intermediate Girls",
    nameAr: "",
    region: "A",
    area: "A",
    academicStage: "Intermediate",
    schoolGender: "Female",
    numberOfStudents: 500,
    status: "active",
  },
  {
    id: "ht-rnd-abt-9b-67",
    nameEn: "Hamad Town Secondary School for Girls",
    nameAr: "مدينة حمد الثانوية للبنات",
    region: "B",
    area: "B",
    academicStage: "Secondary",
    schoolGender: "Female",
    numberOfStudents: 500,
    status: "active",
  },
  {
    id: "isa-town-6-68",
    nameEn: "Isa Town Secondary School for Girls",
    nameAr: "مدينة عيسى الثانوية للبنات",
    region: "ISA TOWN",
    area: "ISA TOWN",
    academicStage: "Secondary",
    schoolGender: "Female",
    numberOfStudents: 500,
    status: "active",
  },
  {
    id: "ht-rnd-abt-2-69",
    nameEn: "Ibn Sina Secondary School for Boys",
    nameAr: "ابن سينا الثانوية للبنين",
    region: "HT RND ABT",
    area: "HT RND ABT",
    academicStage: "Secondary",
    schoolGender: "Male",
    numberOfStudents: 500,
    status: "active",
  },
  {
    id: "muhrq---10-70",
    nameEn: "Muharraq Secondary School for Boys",
    nameAr: "المحرق الثانوية للبنين",
    region: "MUHRQ",
    area: "MUHRQ",
    academicStage: "Secondary",
    schoolGender: "Male",
    numberOfStudents: 500,
    status: "active",
  },
  {
    id: "sitra-1-71",
    nameEn: "Ali Imam Ali ibn aby Talib Primary & Intermediate School for Boys",
    nameAr: "مدرسة الإمام علي الابتدائية الإعدادية للبنين",
    region: "SITRA",
    area: "SITRA",
    academicStage: "Primary",
    schoolGender: "Male",
    numberOfStudents: 500,
    status: "active",
  },
  {
    id: "sitra-2-72",
    nameEn: "Umm Al-Qura Primary & Intermediate School for Girls",
    nameAr: "مدرسة أم القرى الابتدائية الإعدادية للبنات",
    region: "SITRA",
    area: "SITRA",
    academicStage: "Primary",
    schoolGender: "Female",
    numberOfStudents: 500,
    status: "active",
  },
  {
    id: "manama---8-73",
    nameEn: "Al-Hoora Secondary Girls Schools --- مرسة الحورة الثانوية للبنات",
    nameAr: "",
    region: "MANAMA",
    area: "MANAMA",
    academicStage: "Secondary",
    schoolGender: "Female",
    numberOfStudents: 500,
    status: "active",
  },
  {
    id: "isa-town-5-74",
    nameEn: "Al-Wafaa Secondary Girls Schools --- مرسة الوفاء الثانوية للبنات",
    nameAr: "",
    region: "ISA TOWN",
    area: "ISA TOWN",
    academicStage: "Secondary",
    schoolGender: "Female",
    numberOfStudents: 500,
    status: "active",
  },
  {
    id: "manama---7-75",
    nameEn: "Ahmed Al-Omran Secondary Boys Schools --- مزرسة احمد العمران الثانوية للبنين",
    nameAr: "",
    region: "MANAMA",
    area: "MANAMA",
    academicStage: "Secondary",
    schoolGender: "Male",
    numberOfStudents: 500,
    status: "active",
  },
  {
    id: "jidhaf-2-76",
    nameEn: "Jidhafs Secondary Boys School --- جدحفص الثانوية الصناعية للبنين",
    nameAr: "",
    region: "JIDHAF",
    area: "JIDHAF",
    academicStage: "Secondary",
    schoolGender: "Male",
    numberOfStudents: 500,
    status: "active",
  },
  {
    id: "jidhaf-1-77",
    nameEn: "Jidhafs Secondary Girls School --- جدحفص الثانوية للبنات",
    nameAr: "",
    region: "JIDHAF",
    area: "JIDHAF",
    academicStage: "Secondary",
    schoolGender: "Female",
    numberOfStudents: 500,
    status: "active",
  },
  {
    id: "saar---3-78",
    nameEn: "Saar Secondary Girls School ---  مدرسة سار الثانوية للبنات",
    nameAr: "",
    region: "SAAR",
    area: "SAAR",
    academicStage: "Secondary",
    schoolGender: "Female",
    numberOfStudents: 500,
    status: "active",
  },
  {
    id: "manama---10-79",
    nameEn: "Sheikh Abdull Aziz Bin Mohmeed  Secondary Boys School --- مدرسة الشيخ عبدالعزيزبن محمد الثانوية للبنين",
    nameAr: "",
    region: "MANAMA",
    area: "MANAMA",
    academicStage: "Secondary",
    schoolGender: "Male",
    numberOfStudents: 500,
    status: "active",
  },
  {
    id: "isa-town-10-80",
    nameEn: "Ameema bint Al-Nu’man Secondary School for Girls ---  أميمة بنت النعمان الثانوية للبنات",
    nameAr: "",
    region: "ISA TOWN",
    area: "ISA TOWN",
    academicStage: "Secondary",
    schoolGender: "Female",
    numberOfStudents: 500,
    status: "active",
  },
  {
    id: "ht-rnd-abt-22a-81",
    nameEn: "Ibn Tufail Primary School for Boys---مدرسة ابن طفيل الابتدايئة للبنين",
    nameAr: "",
    region: "A",
    area: "A",
    academicStage: "Primary",
    schoolGender: "Male",
    numberOfStudents: 500,
    status: "active",
  },
  {
    id: "isa-town-8-82",
    nameEn: "Al-Khansa Primary School for Girls --- مدرسة الخنساء  الابتدايئة للبنات",
    nameAr: "",
    region: "ISA TOWN",
    area: "ISA TOWN",
    academicStage: "Primary",
    schoolGender: "Female",
    numberOfStudents: 500,
    status: "active",
  },
  {
    id: "ht-rnd-abt-7a-83",
    nameEn: "Al-Rawdha Primary School for Girls---مدرسة الروضة  الابتدايئة للبنات",
    nameAr: "",
    region: "A",
    area: "A",
    academicStage: "Primary",
    schoolGender: "Female",
    numberOfStudents: 500,
    status: "active",
  },
  {
    id: "ht-rnd-abt-7b-84",
    nameEn: "Al-Rawdha Primary School for Boys---مدرسة الروضة  الابتدايئة للبنين",
    nameAr: "",
    region: "B",
    area: "B",
    academicStage: "Primary",
    schoolGender: "Male",
    numberOfStudents: 500,
    status: "active",
  },
  {
    id: "ht-rnd-abt-21a-85",
    nameEn: "Al-Qurain Intermediate School for Girls---مدرسة القيران الاعداية للبنات",
    nameAr: "",
    region: "A",
    area: "A",
    academicStage: "Intermediate",
    schoolGender: "Female",
    numberOfStudents: 500,
    status: "active",
  },
  {
    id: "ht-rnd-abt-20-86",
    nameEn: "Al-Nuza Primary School for Girls---مدرسة النزهة الابتدائية للبنات",
    nameAr: "",
    region: "HT RND ABT",
    area: "HT RND ABT",
    academicStage: "Primary",
    schoolGender: "Female",
    numberOfStudents: 500,
    status: "active",
  },
  {
    id: "ht-rnd-abt-17a-87",
    nameEn: "Al-Wadi Primary School for Boys---مدرسة الوادي الابتدائيه للبنين",
    nameAr: "",
    region: "A",
    area: "A",
    academicStage: "Primary",
    schoolGender: "Male",
    numberOfStudents: 500,
    status: "active",
  },
  {
    id: "isa-town-4-88",
    nameEn: "Umm Kulthum Intermediate School for Girls---مدرسة ام كلثوم الاعدادية للبنات",
    nameAr: "",
    region: "ISA TOWN",
    area: "ISA TOWN",
    academicStage: "Intermediate",
    schoolGender: "Female",
    numberOfStudents: 500,
    status: "active",
  },
  {
    id: "isa-town-11-89",
    nameEn: "Tubli Primary School for Girls---مدرسة توبلي الابتدائية للبنات",
    nameAr: "",
    region: "ISA TOWN",
    area: "ISA TOWN",
    academicStage: "Primary",
    schoolGender: "Female",
    numberOfStudents: 500,
    status: "active",
  },
  {
    id: "isa-town-12-90",
    nameEn: "Tubli Primary School for Boys---مدرسة توبلي الابتدائية للبنين",
    nameAr: "",
    region: "ISA TOWN",
    area: "ISA TOWN",
    academicStage: "Primary",
    schoolGender: "Male",
    numberOfStudents: 500,
    status: "active",
  },
  {
    id: "isa-town-9-91",
    nameEn: "Hafsa Umm Al-Mu’minin Primary School for Girls---مدرسة حفصة ام المؤمنين الابتدائية للبنات",
    nameAr: "",
    region: "ISA TOWN",
    area: "ISA TOWN",
    academicStage: "Primary",
    schoolGender: "Female",
    numberOfStudents: 500,
    status: "active",
  },
  {
    id: "manama---11-92",
    nameEn: "Halima Al-Sa’diya Intermediate School for Girls---مدرسة حليمة السعدية الاعدادية للبنات",
    nameAr: "",
    region: "MANAMA",
    area: "MANAMA",
    academicStage: "Intermediate",
    schoolGender: "Female",
    numberOfStudents: 500,
    status: "active",
  },
  {
    id: "ht-rnd-abt-22b-93",
    nameEn: "Saba Primary School for Girls---مدرسة سبا الابتدائية للبنات",
    nameAr: "",
    region: "B",
    area: "B",
    academicStage: "Primary",
    schoolGender: "Female",
    numberOfStudents: 500,
    status: "active",
  },
  {
    id: "isa-town-14-94",
    nameEn: "Salmbad Primary School for Girls---مدرسة سلماباد الابتدائية للبنات",
    nameAr: "",
    region: "ISA TOWN",
    area: "ISA TOWN",
    academicStage: "Primary",
    schoolGender: "Female",
    numberOfStudents: 500,
    status: "active",
  },
  {
    id: "isa-town-2-95",
    nameEn: "Sanad Primary School for Girls---مدرسة سند الابتدائية للبنات",
    nameAr: "",
    region: "ISA TOWN",
    area: "ISA TOWN",
    academicStage: "Primary",
    schoolGender: "Female",
    numberOfStudents: 500,
    status: "active",
  },
  {
    id: "ht-rnd-abt-17b-96",
    nameEn: "Tolaytola Primary School for Girls---مدرسة طليطلة الابتدائية للبنات",
    nameAr: "",
    region: "B",
    area: "B",
    academicStage: "Primary",
    schoolGender: "Female",
    numberOfStudents: 500,
    status: "active",
  },
  {
    id: "isa-town-7-97",
    nameEn: "Ain Jaloot Primary School for Girls---مدرسة عين جالوت الابتدائية للبنات",
    nameAr: "",
    region: "ISA TOWN",
    area: "ISA TOWN",
    academicStage: "Primary",
    schoolGender: "Female",
    numberOfStudents: 500,
    status: "active",
  },
  {
    id: "zinj-1-98",
    nameEn: "Qurtaiba Intermediate School for Girls---مدرسة قرطبة الاعدادية للبنات",
    nameAr: "",
    region: "ZINJ",
    area: "ZINJ",
    academicStage: "Intermediate",
    schoolGender: "Female",
    numberOfStudents: 500,
    status: "active",
  },
  {
    id: "ht-rnd-abt-11-99",
    nameEn: "Nusaiba bint Ka’ab Primary School for Girls---مدرسة نسيبة بنت كعب الابتدائية للبنات",
    nameAr: "",
    region: "HT RND ABT",
    area: "HT RND ABT",
    academicStage: "Primary",
    schoolGender: "Female",
    numberOfStudents: 500,
    status: "active",
  },
  {
    id: "ht-rnd-abt-3(l)-100",
    nameEn: "Madinat Hamad Intermediate School for Boys---مدرسة مدينة حمد الاعدادية للبنين",
    nameAr: "",
    region: "(L)",
    area: "(L)",
    academicStage: "Intermediate",
    schoolGender: "Male",
    numberOfStudents: 500,
    status: "active",
  },
  {
    id: "ht-rnd-abt-3(r)-101",
    nameEn: "Madinat Hamad Intermediate School for Girls---مدرسة مدينة حمد الاعدادية للبنات",
    nameAr: "",
    region: "(R)",
    area: "(R)",
    academicStage: "Intermediate",
    schoolGender: "Female",
    numberOfStudents: 500,
    status: "active",
  },
  {
    id: "zinj-2-102",
    nameEn: "Al-Jabriya Industrial Secondary School for Boys---الجابرية الثانوية الصناعية للبنين",
    nameAr: "",
    region: "ZINJ",
    area: "ZINJ",
    academicStage: "Secondary",
    schoolGender: "Male",
    numberOfStudents: 500,
    status: "active",
  },
  {
    id: "saar---2-103",
    nameEn: "Al-Shurooq Secondary School for Girls---مدرسة الشروق الثانوية للبنات",
    nameAr: "",
    region: "SAAR",
    area: "SAAR",
    academicStage: "Secondary",
    schoolGender: "Female",
    numberOfStudents: 500,
    status: "active",
  },
  {
    id: "manama---12-104",
    nameEn: "Al-Manama Secondary School for Girls---مدرسة المنامة الثانوية للبنات",
    nameAr: "",
    region: "MANAMA",
    area: "MANAMA",
    academicStage: "Secondary",
    schoolGender: "Female",
    numberOfStudents: 500,
    status: "active",
  },
  {
    id: "manama---13-105",
    nameEn: "Al-Na’eem Secondary School for Girls---مدرسة النعيم الثانوية للبنين",
    nameAr: "",
    region: "MANAMA",
    area: "MANAMA",
    academicStage: "Secondary",
    schoolGender: "Male",
    numberOfStudents: 500,
    status: "active",
  },
  {
    id: "manama---9-106",
    nameEn: "Khawla Secondary School for Girls---مدرسة خولة الثانوية للبنات",
    nameAr: "",
    region: "MANAMA",
    area: "MANAMA",
    academicStage: "Secondary",
    schoolGender: "Female",
    numberOfStudents: 500,
    status: "active",
  },
  {
    id: "galali---6-107",
    nameEn: "Al Hidd  Primary & Intermediate School for Girls --- مدرسة الحد الابتدائية الاعدادية للبنين",
    nameAr: "",
    region: "GALALI",
    area: "GALALI",
    academicStage: "Primary",
    schoolGender: "Male",
    numberOfStudents: 500,
    status: "active",
  },
  {
    id: "galali---7-108",
    nameEn: "Al-Hidd Intermediate School for Girls --- مدرسة الحد الاعدادية للبنات",
    nameAr: "",
    region: "GALALI",
    area: "GALALI",
    academicStage: "Intermediate",
    schoolGender: "Female",
    numberOfStudents: 500,
    status: "active",
  },
  {
    id: "ht-rnd-abt-8a-109",
    nameEn: "Al-Manhal Primary School for Boys---مدرسة المنهل الابتدائية للبنين",
    nameAr: "",
    region: "A",
    area: "A",
    academicStage: "Primary",
    schoolGender: "Male",
    numberOfStudents: 500,
    status: "active",
  },
  {
    id: "ht-rnd-abt-8b-110",
    nameEn: "Sa'ad Bin Abe Waqas Boys Primary school---مدرسة سعد بن ابي وقاص البتدائية للبنين",
    nameAr: "",
    region: "B",
    area: "B",
    academicStage: "Primary",
    schoolGender: "Male",
    numberOfStudents: 500,
    status: "active",
  },
  {
    id: "galali---8-111",
    nameEn: "Al-Hidd Secondary School for Girls",
    nameAr: "",
    region: "GALALI",
    area: "GALALI",
    academicStage: "Secondary",
    schoolGender: "Female",
    numberOfStudents: 500,
    status: "active",
  }
];

/** Get active schools only */
export const getActiveSchools = (): School[] => {
  return SCHOOLS.filter((s) => s.status === "active");
};

/** Get school display name based on language */
export const getSchoolDisplayName = (school: School, lang: string): string => {
  if (lang === "ar" && school.nameAr) return school.nameAr;
  return school.nameEn;
};
