heexport interface School {
  id: string;
  nameEn: string;
  nameAr: string;
  region: string;
  area: string;
  academicStage: string;
  schoolGender: string;
  numberOfStudents: number;
  status: string;
}

export const SCHOOLS: School[] = [
  {
    id: "w-riff-4",
    nameEn: "Al-Fateh Secondary School for Boys",
    nameAr: "الفاتح الثانوية للبنين",
    region: "West Region",
    area: "West Riffa",
    academicStage: "Secondary",
    schoolGender: "Male",
    numberOfStudents: 500,
    status: "active",
  },
  {
    id: "manama-1",
    nameEn: "Al‑Ma'mun Primary School for Boys",
    nameAr: "مدرسة المأمون الابتدائية للبنين",
    region: "Capital",
    area: "Manama",
    academicStage: "Primary",
    schoolGender: "Male",
    numberOfStudents: 500,
    status: "active",
  },
  {
    id: "galali-3",
    nameEn: "Ruqiya Primary School for Girls",
    nameAr: "مدرسة رقية الابتدائية للبنات",
    region: "Muharraq",
    area: "Galali",
    academicStage: "Primary",
    schoolGender: "Female",
    numberOfStudents: 1500,
    status: "active",
  },
  {
    id: "hajiyath-5",
    nameEn: "Fatima bint Al‑Khattab Primary School for Girls",
    nameAr: "مدرسة فاطمة بنت الخطاب الابتدائية للبنات",
    region: "Southern",
    area: "Hajiyath",
    academicStage: "Primary",
    schoolGender: "Female",
    numberOfStudents: 500,
    status: "active",
  },
  {
    id: "hajiyath-3",
    nameEn: "East Riffa Secondary School for Boys",
    nameAr: "الرفاع الشرقي الثانوية للبنين",
    region: "Southern",
    area: "Hajiyath",
    academicStage: "Secondary",
    schoolGender: "Male",
    numberOfStudents: 600,
    status: "active",
  },
  {
    id: "galali-5",
    nameEn: "Qalali Primary School for Boys",
    nameAr: "مدرسة قلالي الابتدائية للبنين",
    region: "Muharraq",
    area: "Galali",
    academicStage: "Primary & Intermediate",
    schoolGender: "Male",
    numberOfStudents: 1100,
    status: "active",
  },
  {
    id: "muhrq-2",
    nameEn: "Busaiteen Primary School for Girls",
    nameAr: "مدرسة السبتين الابتدائية للبنات",
    region: "Muharraq",
    area: "Muharraq",
    academicStage: "Primary",
    schoolGender: "Female",
    numberOfStudents: 700,
    status: "active",
  },
  {
    id: "muhrq-4",
    nameEn: "Busaiteen Intermediate School for Girls",
    nameAr: "مدرسة السبتين الإعدادية للبنات",
    region: "Muharraq",
    area: "Muharraq",
    academicStage: "Intermediate",
    schoolGender: "Female",
    numberOfStudents: 650,
    status: "active",
  },
  {
    id: "muhrq-7",
    nameEn: "Khadija Al‑Kubra Intermediate School for Girls",
    nameAr: "مدرسة خديجة الكبرى الإعدادية للبنات",
    region: "Muharraq",
    area: "Muharraq",
    academicStage: "Intermediate",
    schoolGender: "Female",
    numberOfStudents: 800,
    status: "active",
  },
  {
    id: "muhrq-8",
    nameEn: "Maryam bint Imran Primary School for Girls",
    nameAr: "مدرسة مريم بنت عمران الابتدائية للبنات",
    region: "Muharraq",
    area: "Muharraq",
    academicStage: "Primary",
    schoolGender: "Female",
    numberOfStudents: 600,
    status: "active",
  },
  {
    id: "galali-1",
    nameEn: "Al‑Dair Primary & Intermediate School for Girls",
    nameAr: "مدرسة الدير الابتدائية الإعدادية للبنات",
    region: "Muharraq",
    area: "Galali",
    academicStage: "Primary & Intermediate",
    schoolGender: "Female",
    numberOfStudents: 1200,
    status: "active",
  },
  {
    id: "galali-2",
    nameEn: "Al‑Dair Primary School for Boys",
    nameAr: "مدرسة الدير الابتدائية للبنين",
    region: "Muharraq",
    area: "Galali",
    academicStage: "Primary",
    schoolGender: "Male",
    numberOfStudents: 693,
    status: "active",
  },
  {
    id: "arad-1",
    nameEn: "Al‑Khwarizmi Primary School for Boys",
    nameAr: "مدرسة الخوارزمي الابتدائية للبنين",
    region: "Muharraq",
    area: "Arad",
    academicStage: "Primary",
    schoolGender: "Male",
    numberOfStudents: 750,
    status: "active",
  },
  {
    id: "arad-3",
    nameEn: "Arad Primary School for Boys",
    nameAr: "مدرسة عراد الابتدائية للبنين",
    region: "Muharraq",
    area: "Arad",
    academicStage: "Primary",
    schoolGender: "Male",
    numberOfStudents: 359,
    status: "active",
  },
  {
    id: "arad-4",
    nameEn: "Arad Primary School for Girls",
    nameAr: "مدرسة عراد الابتدائية للبنات",
    region: "Muharraq",
    area: "Arad",
    academicStage: "Primary",
    schoolGender: "Female",
    numberOfStudents: 604,
    status: "active",
  },
  {
    id: "arad-2",
    nameEn: "Arad Intermediate School for Girls",
    nameAr: "مدرسة عراد الإعدادية للبنين",
    region: "Muharraq",
    area: "Arad",
    academicStage: "Intermediate",
    schoolGender: "Female",
    numberOfStudents: 891,
    status: "active",
  },
  {
    id: "arad-6",
    nameEn: "Al‑Rawba Primary School for Girls",
    nameAr: "مدرسة العروبة الابتدائية للبنات",
    region: "Muharraq",
    area: "Arad",
    academicStage: "Primary",
    schoolGender: "Female",
    numberOfStudents: 1100,
    status: "active",
  },
  {
    id: "w-riff-1",
    nameEn: "East Riffa Primary School for Boys",
    nameAr: "مدرسة الرفاع الشرقي الابتدائية للبنين",
    region: "Southern",
    area: "West Riffa",
    academicStage: "Primary",
    schoolGender: "Male",
    numberOfStudents: 550,
    status: "active",
  },
  {
    id: "w-riff-2",
    nameEn: "Huneniya Primary School for Girls",
    nameAr: "مدرسة الحينية الابتدائية الإعدادية للبنات",
    region: "Southern",
    area: "West Riffa",
    academicStage: "Primary & Intermediate",
    schoolGender: "Female",
    numberOfStudents: 800,
    status: "active",
  },
  {
    id: "w-riff-5",
    nameEn: "West Riffa Primary School for Girls",
    nameAr: "مدرسة الرفاع الغربي الابتدائية للبنات",
    region: "Southern",
    area: "West Riffa",
    academicStage: "Primary",
    schoolGender: "Female",
    numberOfStudents: 700,
    status: "active",
  },
  {
    id: "w-riff-6",
    nameEn: "West Riffa Primary School for Boys",
    nameAr: "مدرسة الرفاع الغربي الابتدائية للبنين",
    region: "Southern",
    area: "West Riffa",
    academicStage: "Primary",
    schoolGender: "Male",
    numberOfStudents: 600,
    status: "active",
  },
  {
    id: "w-riff-7",
    nameEn: "East Riffa Primary School for Girls",
    nameAr: "مدرسة الرفاع الشرقي الابتدائية للبنات",
    region: "Southern",
    area: "West Riffa",
    academicStage: "Primary",
    schoolGender: "Female",
    numberOfStudents: 650,
    status: "active",
  },
  {
    id: "w-riff-8",
    nameEn: "West Riffa Secondary School for Girls",
    nameAr: "الرفاع الغربي الثانوية للبنات",
    region: "Southern",
    area: "West Riffa",
    academicStage: "Secondary",
    schoolGender: "Female",
    numberOfStudents: 750,
    status: "active",
  },
  {
    id: "w-riff-9",
    nameEn: "West Riffa Intermediate School for Girls",
    nameAr: "مدرسة الرفاع الغربي الإعدادية للبنات",
    region: "Southern",
    area: "West Riffa",
    academicStage: "Intermediate",
    schoolGender: "Female",
    numberOfStudents: 700,
    status: "active",
  },
  {
    id: "hajiyath-1",
    nameEn: "Al-Andalus Primary School for Girls",
    nameAr: "مدرسة الأندلس الابتدائية للبنات",
    region: "Southern",
    area: "Hajiyath",
    academicStage: "Primary",
    schoolGender: "Female",
    numberOfStudents: 550,
    status: "active",
  },
  {
    id: "hajiyath-4",
    nameEn: "Salah Al‑Din Al‑Ayyubi Primary School for Boys",
    nameAr: "مدرسة صلاح الدين الأيوبي الابتدائية للبنين",
    region: "Southern",
    area: "Hajiyath",
    academicStage: "Primary",
    schoolGender: "Male",
    numberOfStudents: 600,
    status: "active",
  },
  {
    id: "hajiyath-6",
    nameEn: "East Riffa Intermediate School for Girls",
    nameAr: "مدرسة الرفاع الشرقي الإعدادية للبنات",
    region: "Southern",
    area: "Hajiyath",
    academicStage: "Intermediate",
    schoolGender: "Female",
    numberOfStudents: 700,
    status: "active",
  },
  {
    id: "reem-1",
    nameEn: "Riffa Intermediate School for Boys",
    nameAr: "مدرسة الرفاع الإعدادية للبنين",
    region: "Southern",
    area: "Reem",
    academicStage: "Intermediate",
    schoolGender: "Male",
    numberOfStudents: 650,
    status: "active",
  },
  {
    id: "w-riff-3",
    nameEn: "Ibn Rushd Primary & Intermediate School for Boys",
    nameAr: "مدرسة ابن رشد الابتدائية الإعدادية للبنين",
    region: "Southern",
    area: "West Riffa",
    academicStage: "Primary & Intermediate",
    schoolGender: "Male",
    numberOfStudents: 850,
    status: "active",
  },
  {
    id: "hmdtown-2",
    nameEn: "Safra Primary School for Boys",
    nameAr: "مدرسة سافرة الابتدائية الإعدادية للبنين",
    region: "Northern",
    area: "Hamad Town",
    academicStage: "Primary & Intermediate",
    schoolGender: "Male",
    numberOfStudents: 700,
    status: "active",
  },
  {
    id: "riffa-3",
    nameEn: "Wadi Al‑Seel Primary & Intermediate School for Boys",
    nameAr: "مدرسة وادي السيل الابتدائية الإعدادية للبنين",
    region: "Southern",
    area: "Riffa",
    academicStage: "Primary & Intermediate",
    schoolGender: "Male",
    numberOfStudents: 750,
    status: "active",
  },
  {
    id: "muhrq-1",
    nameEn: "Al-Hidaya Al-Khalifia Secondary School for Boys",
    nameAr: "الهداية الخليفية الثانوية للبنين",
    region: "Muharraq",
    area: "Muharraq",
    academicStage: "Secondary",
    schoolGender: "Male",
    numberOfStudents: 800,
    status: "active",
  },
  {
    id: "muhrq-6",
    nameEn: "Sheikh Khalifa Bin Salman Institute of Technogy",
    nameAr: "معهد الشيخ خليفة بن سلمان للتكنولوجيا",
    region: "Muharraq",
    area: "Muharraq",
    academicStage: "Vocational",
    schoolGender: "Male",
    numberOfStudents: 600,
    status: "active",
  },
  {
    id: "muhrq-9",
    nameEn: "Omar bin Al‑Khattab Primary & Intermediate School for Boys",
    nameAr: "عمر بن الخطاب الابتدائية الإعدادية للبنين",
    region: "Muharraq",
    area: "Muharraq",
    academicStage: "Primary & Intermediate",
    schoolGender: "Male",
    numberOfStudents: 850,
    status: "active",
  },
  {
    id: "galali-4",
    nameEn: "Samaheej Intermediate School for Boys",
    nameAr: "مدرسة سماهيج الإعدادية للبنين",
    region: "Muharraq",
    area: "Galali",
    academicStage: "Intermediate",
    schoolGender: "Male",
    numberOfStudents: 660,
    status: "active",
  },
  {
    id: "arad-5",
    nameEn: "Arad Intermediate School for Boys",
    nameAr: "مدرسة عراد الإعدادية للبنين",
    region: "Muharraq",
    area: "Arad",
    academicStage: "Intermediate",
    schoolGender: "Male",
    numberOfStudents: 880,
    status: "active",
  },
  {
    id: "muhrq-3",
    nameEn: "Busaiteen Primary School for Boys",
    nameAr: "مدرسة السبتين الابتدائية للبنين",
    region: "Muharraq",
    area: "Muharraq",
    academicStage: "Primary",
    schoolGender: "Male",
    numberOfStudents: 600,
    status: "active",
  },
  {
    id: "muhrq-5",
    nameEn: "Busaiteen Intermediate School for Boys",
    nameAr: "مدرسة السبتين الإعدادية للبنين",
    region: "Muharraq",
    area: "Muharraq",
    academicStage: "Intermediate",
    schoolGender: "Male",
    numberOfStudents: 700,
    status: "active",
  },
  {
    id: "asker-2",
    nameEn: "Jaw Primary School for Boys",
    nameAr: "مدرسة جو الابتدائية للبنين",
    region: "Southern",
    area: "Asker",
    academicStage: "Primary",
    schoolGender: "Male",
    numberOfStudents: 500,
    status: "active",
  },
  {
    id: "hajiyath-2",
    nameEn: "Malik bin Anas Primary School for Boys",
    nameAr: "مدرسة مالك بن أنس الابتدائية للبنين",
    region: "Southern",
    area: "Hajiyath",
    academicStage: "Primary",
    schoolGender: "Male",
    numberOfStudents: 550,
    status: "active",
  },
  {
    id: "riffa-1",
    nameEn: "Safra Intermediate School for Girls",
    nameAr: "مدرسة سافرة الابتدائية الإعدادية للبنات",
    region: "Southern",
    area: "Riffa",
    academicStage: "Intermediate",
    schoolGender: "Female",
    numberOfStudents: 650,
    status: "active",
  },
  {
    id: "riffa-4",
    nameEn: "Buri Primary School for Girls",
    nameAr: "مدرسة بوري الابتدائية للبنات",
    region: "Southern",
    area: "Riffa",
    academicStage: "Primary",
    schoolGender: "Female",
    numberOfStudents: 500,
    status: "active",
  },
  {
    id: "riffa-5",
    nameEn: "Buri Primary School for Boys",
    nameAr: "مدرسة بوري الابتدائية للبنين",
    region: "Southern",
    area: "Riffa",
    academicStage: "Primary",
    schoolGender: "Male",
    numberOfStudents: 500,
    status: "active",
  },
  {
    id: "hmdtown-6",
    nameEn: "Tadamon School Girls",
    nameAr: "التضامن الثانوية للبنات",
    region: "Northern",
    area: "Hamad Town",
    academicStage: "Secondary",
    schoolGender: "Female",
    numberOfStudents: 700,
    status: "active",
  },
  {
    id: "saar-1",
    nameEn: "Aljazra School Boys",
    nameAr: "مدرسة الجسرة الابتدائية للبنين",
    region: "Northern",
    area: "Saar",
    academicStage: "Primary",
    schoolGender: "Male",
    numberOfStudents: 550,
    status: "active",
  },
  {
    id: "manama-2",
    nameEn: "AlMutanabi Primary Boys School",
    nameAr: "مدرسة المتنبي الابتدائية للبنين",
    region: "Capital",
    area: "Manama",
    academicStage: "Primary",
    schoolGender: "Male",
    numberOfStudents: 500,
    status: "active",
  },
  {
    id: "manama-3",
    nameEn: "Rabi'a Al‑Adawiya Primary School for Girls",
    nameAr: "مدرسة رابعة العدوية الابتدائية للبنات",
    region: "Capital",
    area: "Manama",
    academicStage: "Primary",
    schoolGender: "Female",
    numberOfStudents: 500,
    status: "active",
  },
  {
    id: "manama-4",
    nameEn: "Sukaina bint Al‑Hussain Primary School for Girls",
    nameAr: "مدرسة سكينة بنت الحسين الابتدائية للبنات",
    region: "Capital",
    area: "Manama",
    academicStage: "Primary",
    schoolGender: "Female",
    numberOfStudents: 500,
    status: "active",
  },
  {
    id: "manama-5",
    nameEn: "Aisha Umm Al‑Mu'mineen Primary School for Girls",
    nameAr: "مدرسة عائشة أم المؤمنين الابتدائية للبنات",
    region: "Capital",
    area: "Manama",
    academicStage: "Primary",
    schoolGender: "Female",
    numberOfStudents: 500,
    status: "active",
  },
  {
    id: "manama-6",
    nameEn: "Umm Ayman Primary school for Girls",
    nameAr: "مدرسة أم أيمن الابتدائية للبنات",
    region: "Capital",
    area: "Manama",
    academicStage: "Primary",
    schoolGender: "Female",
    numberOfStudents: 500,
    status: "active",
  },
  {
    id: "reem-2",
    nameEn: "Al-Ma'arifa Secondary School for Girls",
    nameAr: "المعرفة الثانوية للبنات",
    region: "Southern",
    area: "Reem",
    academicStage: "Secondary",
    schoolGender: "Female",
    numberOfStudents: 600,
    status: "active",
  },
  {
    id: "reem-3",
    nameEn: "Al‑Mustaqbal Primary School for Girls",
    nameAr: "مدرسة المستقبل الابتدائية للبنات",
    region: "Southern",
    area: "Reem",
    academicStage: "Primary",
    schoolGender: "Female",
    numberOfStudents: 550,
    status: "active",
  },
  {
    id: "reem-4",
    nameEn: "Uqba bin Nafi Primary School for Boys",
    nameAr: "مدرسة عقبة بن نافع الابتدائية للبنين",
    region: "Southern",
    area: "Reem",
    academicStage: "Primary",
    schoolGender: "Male",
    numberOfStudents: 500,
    status: "active",
  },
  {
    id: "reem-5",
    nameEn: "Arabian Gulf Primary School for Girls",
    nameAr: "مدرسة الخليج العربي الإعدادية للبنات",
    region: "Southern",
    area: "Reem",
    academicStage: "Intermediate",
    schoolGender: "Female",
    numberOfStudents: 600,
    status: "active",
  },
  {
    id: "asker-1b",
    nameEn: "H.H. Shaikha Moza bint Hamad Al Khalifa Primary School (Girls) - 2",
    nameAr: "مدرسة سمو الشيخة موزة بنت حمد آل خليفة الابتدائية للبنات - 2",
    region: "Southern",
    area: "Asker",
    academicStage: "Primary",
    schoolGender: "Female",
    numberOfStudents: 1600,
    status: "active",
  },
  {
    id: "asker-3",
    nameEn: "Askar Primary & Intermediate School for Boys",
    nameAr: "مدرسة عسكر الابتدائية للبنين",
    region: "Southern",
    area: "Asker",
    academicStage: "Primary & Intermediate",
    schoolGender: "Male",
    numberOfStudents: 600,
    status: "active",
  },
  {
    id: "w-riff-10",
    nameEn: "Ahmed Al‑Fateh Primary & Intermediate School for Boys",
    nameAr: "مدرسة أحمد الفاتح الابتدائية الإعدادية للبنين",
    region: "Southern",
    area: "West Riffa",
    academicStage: "Primary & Intermediate",
    schoolGender: "Male",
    numberOfStudents: 800,
    status: "active",
  },
  {
    id: "asker-1a",
    nameEn: "H.H. Shaikha Moza bint Hamad Al Khalifa Primary School (Girls) - 1",
    nameAr: "مدرسة سمو الشيخة موزة بنت حمد آل خليفة الابتدائية للبنات - 1",
    region: "Southern",
    area: "Asker",
    academicStage: "Primary",
    schoolGender: "Female",
    numberOfStudents: 1600,
    status: "active",
  },
  {
    id: "asker-1c",
    nameEn: "H.H. Shaikha Moza bint Hamad Al Khalifa Intermediate School (Girls)",
    nameAr: "مدرسة سمو الشيخة موزة بنت حمد آل خليفة الإعدادية للبنات",
    region: "Southern",
    area: "Asker",
    academicStage: "Intermediate",
    schoolGender: "Female",
    numberOfStudents: 1600,
    status: "active",
  },
  {
    id: "asker-1",
    nameEn: "H.H. Shaikha Moza bint Hamad Al Khalifa Secondary School (Girls)",
    nameAr: "مدرسة سمو الشيخة موزة بنت حمد آل خليفة الثانوية للبنات",
    region: "Southern",
    area: "Asker",
    academicStage: "Secondary",
    schoolGender: "Female",
    numberOfStudents: 1600,
    status: "active",
  },
  {
    id: "sample-school-2",
    nameEn: "2 Sample School",
    nameAr: "مدرسة نموذجية 2",
    region: "Central",
    area: "Sample Area",
    academicStage: "Primary",
    schoolGender: "Mixed",
    numberOfStudents: 300,
    status: "active",
  },
  {
    id: "asker-4",
    nameEn: "Shaikh Nasser Center For Science & Technology",
    nameAr: "مركز الشيخ ناصر للعلوم والتكنولوجيا",
    region: "Southern",
    area: "Asker",
    academicStage: "Vocational",
    schoolGender: "Male",
    numberOfStudents: 600,
    status: "active",
  },
  {
    id: "isatown-1",
    nameEn: "Al-Taawun Secondary School for Boys",
    nameAr: "التعاون الثانوية للبنين",
    region: "Northern",
    area: "Isa Town",
    academicStage: "Secondary",
    schoolGender: "Male",
    numberOfStudents: 700,
    status: "active",
  },
  {
    id: "isatown-13",
    nameEn: "Sheikh Isa bin Ali Secondary School for Boys",
    nameAr: "الشيخ عيسى بن علي الثانوية للبنين",
    region: "Northern",
    area: "Isa Town",
    academicStage: "Secondary",
    schoolGender: "Male",
    numberOfStudents: 750,
    status: "active",
  },
  {
    id: "isatown-3",
    nameEn: "Al-Noor Secondary School for Girls",
    nameAr: "النور الثانوية للبنات",
    region: "Northern",
    area: "Isa Town",
    academicStage: "Secondary",
    schoolGender: "Female",
    numberOfStudents: 650,
    status: "active",
  },
  {
    id: "ht-rnd-abt-4",
    nameEn: "Ghazi Al-Qusaibi Secondary School for Girls",
    nameAr: "غازي القصيبي الثانوية للبنات",
    region: "Northern",
    area: "Hamad Town",
    academicStage: "Secondary",
    schoolGender: "Female",
    numberOfStudents: 700,
    status: "active",
  },
  {
    id: "ht-rnd-abt-9a",
    nameEn: "Yathrib Intermediate Girls",
    nameAr: "يثرب الإعدادية للبنات",
    region: "Northern",
    area: "Hamad Town",
    academicStage: "Intermediate",
    schoolGender: "Female",
    numberOfStudents: 650,
    status: "active",
  },
  {
    id: "ht-rnd-abt-9b",
    nameEn: "Hamad Town Secondary School for Girls",
    nameAr: "مدينة حمد الثانوية للبنات",
    region: "Northern",
    area: "Hamad Town",
    academicStage: "Secondary",
    schoolGender: "Female",
    numberOfStudents: 800,
    status: "active",
  },
  {
    id: "isatown-6",
    nameEn: "Isa Town Secondary School for Girls",
    nameAr: "مدينة عيسى الثانوية للبنات",
    region: "Northern",
    area: "Isa Town",
    academicStage: "Secondary",
    schoolGender: "Female",
    numberOfStudents: 700,
    status: "active",
  },
  {
    id: "ht-rnd-abt-2",
    nameEn: "Ibn Sina Secondary School for Boys",
    nameAr: "ابن سينا الثانوية للبنين",
    region: "Northern",
    area: "Hamad Town",
    academicStage: "Secondary",
    schoolGender: "Male",
    numberOfStudents: 750,
    status: "active",
  },
  {
    id: "muhrq-10",
    nameEn: "Muharraq Secondary School for Boys",
    nameAr: "المحرق الثانوية للبنين",
    region: "Muharraq",
    area: "Muharraq",
    academicStage: "Secondary",
    schoolGender: "Male",
    numberOfStudents: 900,
    status: "active",
  },
  {
    id: "sitra-1",
    nameEn: "Ali Imam Ali ibn aby Talib Primary & Intermediate School for Boys",
    nameAr: "مدرسة الإمام علي الابتدائية الإعدادية للبنين",
    region: "Central",
    area: "Sitra",
    academicStage: "Primary & Intermediate",
    schoolGender: "Male",
    numberOfStudents: 800,
    status: "active",
  },
  {
    id: "sitra-2",
    nameEn: "Umm Al-Qura Primary & Intermediate School for Girls",
    nameAr: "مدرسة أم القرى الابتدائية الإعدادية للبنات",
    region: "Central",
    area: "Sitra",
    academicStage: "Primary & Intermediate",
    schoolGender: "Female",
    numberOfStudents: 750,
    status: "active",
  },
  {
    id: "manama-8",
    nameEn: "Al-Hoora Secondary Girls Schools",
    nameAr: "مرسة الحورة الثانوية للبنات",
    region: "Capital",
    area: "Manama",
    academicStage: "Secondary",
    schoolGender: "Female",
    numberOfStudents: 700,
    status: "active",
  },
  {
    id: "isatown-5",
    nameEn: "Al-Wafaa Secondary Girls Schools",
    nameAr: "مرسة الوفاء الثانوية للبنات",
    region: "Northern",
    area: "Isa Town",
    academicStage: "Secondary",
    schoolGender: "Female",
    numberOfStudents: 650,
    status: "active",
  },
  {
    id: "manama-7",
    nameEn: "Ahmed Al-Omran Secondary Boys Schools",
    nameAr: "مزرسة احمد العمران الثانوية للبنين",
    region: "Capital",
    area: "Manama",
    academicStage: "Secondary",
    schoolGender: "Male",
    numberOfStudents: 700,
    status: "active",
  },
  {
    id: "jidhaf-2",
    nameEn: "Jidhafs Secondary Boys School",
    nameAr: "جدحفص الثانوية الصناعية للبنين",
    region: "Northern",
    area: "Jidhafs",
    academicStage: "Secondary Vocational",
    schoolGender: "Male",
    numberOfStudents: 600,
    status: "active",
  },
  {
    id: "jidhaf-1",
    nameEn: "Jidhafs Secondary Girls School",
    nameAr: "جدحفص الثانوية للبنات",
    region: "Northern",
    area: "Jidhafs",
    academicStage: "Secondary",
    schoolGender: "Female",
    numberOfStudents: 650,
    status: "active",
  },
  {
    id: "saar-3",
    nameEn: "Saar Secondary Girls School",
    nameAr: "مدرسة سار الثانوية للبنات",
    region: "Northern",
    area: "Saar",
    academicStage: "Secondary",
    schoolGender: "Female",
    numberOfStudents: 600,
    status: "active",
  },
  {
    id: "manama-10",
    nameEn: "Sheikh Abdull Aziz Bin Mohmeed Secondary Boys School",
    nameAr: "مدرسة الشيخ عبدالعزيزبن محمد الثانوية للبنين",
    region: "Capital",
    area: "Manama",
    academicStage: "Secondary",
    schoolGender: "Male",
    numberOfStudents: 750,
    status: "active",
  },
  {
    id: "isatown-10",
    nameEn: "Ameema bint Al-Nu'man Secondary School for Girls",
    nameAr: "أميمة بنت النعمان الثانوية للبنات",
    region: "Northern",
    area: "Isa Town",
    academicStage: "Secondary",
    schoolGender: "Female",
    numberOfStudents: 650,
    status: "active",
  },
  {
    id: "ht-rnd-abt-22a",
    nameEn: "Ibn Tufail Primary School for Boys",
    nameAr: "مدرسة ابن طفيل الابتدايئة للبنين",
    region: "Northern",
    area: "Hamad Town",
    academicStage: "Primary",
    schoolGender: "Male",
    numberOfStudents: 500,
    status: "active",
  },
  {
    id: "isatown-8",
    nameEn: "Al-Khansa Primary School for Girls",
    nameAr: "مدرسة الخنساء الابتدايئة للبنات",
    region: "Northern",
    area: "Isa Town",
    academicStage: "Primary",
    schoolGender: "Female",
    numberOfStudents: 500,
    status: "active",
  },
  {
    id: "ht-rnd-abt-7a",
    nameEn: "Al-Rawdha Primary School for Girls",
    nameAr: "مدرسة الروضة الابتدايئة للبنات",
    region: "Northern",
    area: "Hamad Town",
    academicStage: "Primary",
    schoolGender: "Female",
    numberOfStudents: 550,
    status: "active",
  },
  {
    id: "ht-rnd-abt-7b",
    nameEn: "Al-Rawdha Primary School for Boys",
    nameAr: "مدرسة الروضة الابتدايئة للبنين",
    region: "Northern",
    area: "Hamad Town",
    academicStage: "Primary",
    schoolGender: "Male",
    numberOfStudents: 550,
    status: "active",
  },
  {
    id: "ht-rnd-abt-21a",
    nameEn: "Al-Qurain Intermediate School for Girls",
    nameAr: "مدرسة القيران الاعداية للبنات",
    region: "Northern",
    area: "Hamad Town",
    academicStage: "Intermediate",
    schoolGender: "Female",
    numberOfStudents: 600,
    status: "active",
  },
  {
    id: "ht-rnd-abt-20",
    nameEn: "Al-Nuza Primary School for Girls",
    nameAr: "مدرسة النزهة الابتدائية للبنات",
    region: "Northern",
    area: "Hamad Town",
    academicStage: "Primary",
    schoolGender: "Female",
    numberOfStudents: 500,
    status: "active",
  },
  {
    id: "ht-rnd-abt-17a",
    nameEn: "Al-Wadi Primary School for Boys",
    nameAr: "مدرسة الوادي الابتدائيه للبنين",
    region: "Northern",
    area: "Hamad Town",
    academicStage: "Primary",
    schoolGender: "Male",
    numberOfStudents: 500,
    status: "active",
  },
  {
    id: "isatown-4",
    nameEn: "Umm Kulthum Intermediate School for Girls",
    nameAr: "مدرسة ام كلثوم الاعدادية للبنات",
    region: "Northern",
    area: "Isa Town",
    academicStage: "Intermediate",
    schoolGender: "Female",
    numberOfStudents: 600,
    status: "active",
  },
  {
    id: "isatown-11",
    nameEn: "Tubli Primary School for Girls",
    nameAr: "مدرسة توبلي الابتدائية للبنات",
    region: "Northern",
    area: "Isa Town",
    academicStage: "Primary",
    schoolGender: "Female",
    numberOfStudents: 500,
    status: "active",
  },
  {
    id: "isatown-12",
    nameEn: "Tubli Primary School for Boys",
    nameAr: "مدرسة توبلي الابتدائية للبنين",
    region: "Northern",
    area: "Isa Town",
    academicStage: "Primary",
    schoolGender: "Male",
    numberOfStudents: 500,
    status: "active",
  },
  {
    id: "isatown-9",
    nameEn: "Hafsa Umm Al-Mu'minin Primary School for Girls",
    nameAr: "مدرسة حفصة ام المؤمنين الابتدائية للبنات",
    region: "Northern",
    area: "Isa Town",
    academicStage: "Primary",
    schoolGender: "Female",
    numberOfStudents: 500,
    status: "active",
  },
  {
    id: "manama-11",
    nameEn: "Halima Al-Sa'diya Intermediate School for Girls",
    nameAr: "مدرسة حليمة السعدية الاعدادية للبنات",
    region: "Capital",
    area: "Manama",
    academicStage: "Intermediate",
    schoolGender: "Female",
    numberOfStudents: 600,
    status: "active",
  },
  {
    id: "ht-rnd-abt-22b",
    nameEn: "Saba Primary School for Girls",
    nameAr: "مدرسة سبا الابتدائية للبنات",
    region: "Northern",
    area: "Hamad Town",
    academicStage: "Primary",
    schoolGender: "Female",
    numberOfStudents: 500,
    status: "active",
  },
  {
    id: "isatown-14",
    nameEn: "Salmbad Primary School for Girls",
    nameAr: "مدرسة سلماباد الابتدائية للبنات",
    region: "Northern",
    area: "Isa Town",
    academicStage: "Primary",
    schoolGender: "Female",
    numberOfStudents: 500,
    status: "active",
  },
  {
    id: "isatown-2",
    nameEn: "Sanad Primary School for Girls",
    nameAr: "مدرسة سند الابتدائية للبنات",
    region: "Northern",
    area: "Isa Town",
    academicStage: "Primary",
    schoolGender: "Female",
    numberOfStudents: 500,
    status: "active",
  },
  {
    id: "ht-rnd-abt-17b",
    nameEn: "Tolaytola Primary School for Girls",
    nameAr: "مدرسة طليطلة الابتدائية للبنات",
    region: "Northern",
    area: "Hamad Town",
    academicStage: "Primary",
    schoolGender: "Female",
    numberOfStudents: 500,
    status: "active",
  },
  {
    id: "isatown-7",
    nameEn: "Ain Jaloot Primary School for Girls",
    nameAr: "مدرسة عين جالوت الابتدائية للبنات",
    region: "Northern",
    area: "Isa Town",
    academicStage: "Primary",
    schoolGender: "Female",
    numberOfStudents: 500,
    status: "active",
  },
  {
    id: "zinj-1",
    nameEn: "Qurtaiba Intermediate School for Girls",
    nameAr: "مدرسة قرطبة الاعدادية للبنات",
    region: "Capital",
    area: "Zinj",
    academicStage: "Intermediate",
    schoolGender: "Female",
    numberOfStudents: 600,
    status: "active",
  },
  {
    id: "ht-rnd-abt-11",
    nameEn: "Nusaiba bint Ka'ab Primary School for Girls",
    nameAr: "مدرسة نسيبة بنت كعب الابتدائية للبنات",
    region: "Northern",
    area: "Hamad Town",
    academicStage: "Primary",
    schoolGender: "Female",
    numberOfStudents: 500,
    status: "active",
  },
  {
    id: "ht-rnd-abt-3l",
    nameEn: "Madinat Hamad Intermediate School for Boys",
    nameAr: "مدرسة مدينة حمد الاعدادية للبنين",
    region: "Northern",
    area: "Hamad Town",
    academicStage: "Intermediate",
    schoolGender: "Male",
    numberOfStudents: 700,
    status: "active",
  },
  {
    id: "ht-rnd-abt-3r",
    nameEn: "Madinat Hamad Intermediate School for Girls",
    nameAr: "مدرسة مدينة حمد الاعدادية للبنات",
    region: "Northern",
    area: "Hamad Town",
    academicStage: "Intermediate",
    schoolGender: "Female",
    numberOfStudents: 700,
    status: "active",
  },
  {
    id: "zinj-2",
    nameEn: "Al-Jabriya Industrial Secondary School for Boys",
    nameAr: "الجابرية الثانوية الصناعية للبنين",
    region: "Capital",
    area: "Zinj",
    academicStage: "Secondary Vocational",
    schoolGender: "Male",
    numberOfStudents: 650,
    status: "active",
  },
  {
    id: "saar-2",
    nameEn: "Al-Shurooq Secondary School for Girls",
    nameAr: "مدرسة الشروق الثانوية للبنات",
    region: "Northern",
    area: "Saar",
    academicStage: "Secondary",
    schoolGender: "Female",
    numberOfStudents: 650,
    status: "active",
  },
  {
    id: "manama-12",
    nameEn: "Al-Manama Secondary School for Girls",
    nameAr: "مدرسة المنامة الثانوية للبنات",
    region: "Capital",
    area: "Manama",
    academicStage: "Secondary",
    schoolGender: "Female",
    numberOfStudents: 700,
    status: "active",
  },
  {
    id: "manama-13",
    nameEn: "Al-Na'eem Secondary School for Girls",
    nameAr: "مدرسة النعيم الثانوية للبنين",
    region: "Capital",
    area: "Manama",
    academicStage: "Secondary",
    schoolGender: "Female",
    numberOfStudents: 700,
    status: "active",
  },
  {
    id: "manama-9",
    nameEn: "Khawla Secondary School for Girls",
    nameAr: "مدرسة خولة الثانوية للبنات",
    region: "Capital",
    area: "Manama",
    academicStage: "Secondary",
    schoolGender: "Female",
    numberOfStudents: 650,
    status: "active",
  },
  {
    id: "galali-6",
    nameEn: "Al Hidd Primary & Intermediate School for Girls",
    nameAr: "مدرسة الحد الابتدائية الاعدادية للبنين",
    region: "Muharraq",
    area: "Galali",
    academicStage: "Primary & Intermediate",
    schoolGender: "Female",
    numberOfStudents: 1571,
    status: "active",
  },
  {
    id: "galali-7",
    nameEn: "Al-Hidd Intermediate School for Girls",
    nameAr: "مدرسة الحد الاعدادية للبنات",
    region: "Muharraq",
    area: "Galali",
    academicStage: "Intermediate",
    schoolGender: "Female",
    numberOfStudents: 800,
    status: "active",
  },
  {
    id: "ht-rnd-abt-8a",
    nameEn: "Al-Manhal Primary School for Boys",
    nameAr: "مدرسة المنهل الابتدائية للبنين",
    region: "Northern",
    area: "Hamad Town",
    academicStage: "Primary",
    schoolGender: "Male",
    numberOfStudents: 550,
    status: "active",
  },
  {
    id: "ht-rnd-abt-8b",
    nameEn: "Sa'ad Bin Abe Waqas Boys Primary school",
    nameAr: "مدرسة سعد بن ابي وقاص البتدائية للبنين",
    region: "Northern",
    area: "Hamad Town",
    academicStage: "Primary",
    schoolGender: "Male",
    numberOfStudents: 550,
    status: "active",
  },
  {
    id: "galali-8",
    nameEn: "Al-Hidd Secondary School for Girls",
    nameAr: "مدرسة الحد الثانوية للبنات",
    region: "Muharraq",
    area: "Galali",
    academicStage: "Secondary",
    schoolGender: "Female",
    numberOfStudents: 750,
    status: "active",
  },
];

/** Get active schools only */
export const getActiveSchools = (): School[] => {
  return SCHOOLS.filter((s) => s.status === "active");
};

/** Get school display name based on language */
export const getSchoolDisplayName = (school: School, lang: string): string => {
  if (lang === "ar" && school.nameAr) return school.nameAr;
  return school.nameEn;
};
